2.7.0

diff --git a/findent/bin/wfindent b/findent/bin/wfindent
--- a/findent/bin/wfindent
+++ b/findent/bin/wfindent
@@ -1,5 +1,6 @@
 #!/bin/sh
-# $Id: wfindent 92 2015-08-04 03:08:54Z willem_vermin $
+# $Id: wfindent.tmpl 145 2016-11-13 16:16:33Z willem_vermin $
+# vim: filetype=sh
 #
 # in-place indenting of fortran sources using findent
 # example:
@@ -11,8 +12,17 @@
 # otherwize an error message is printed.
 #
 
-FINDENT=findent
-parms=$( getopt -o a:b:c:C:d:e:E:f:F:hHi:I:j:l:L:m:o:qr:R:s:t:vw:x: -- "$@" )
+# the location of findent, replace with correct location:
+FINDENT="/home/willem/sourceforge/findent-code/trunk/findent/bin/findent"
+if ! "$FINDENT" -v >/dev/null 2>&1 ; then
+   FINDENT="findent"   # try if findent is in PATH
+   if ! "$FINDENT" -v >/dev/null 2>&1 ; then
+      echo "$0: findent not found, exiting"
+      exit 1
+   fi
+fi
+echo "$0 using: "`"$FINDENT" -v`
+parms=$( getopt -o a:b:c:C:d:e:E:f:F:hHi:I:j:k:l:L:m:o:qr:R:s:t:vw:x: -- "$@" )
 if [ $? -ne 0 ] ; then
    exit 1
 fi
@@ -23,9 +33,25 @@ while [ "$1" ] ; do
       --) shift
 	  break
 	  ;;
-      *) fparms="$fparms $1" 
-	  shift
-	  ;;
+      *) if [ "$1" = "-v" ] ; then
+	    echo "wfindent using $FINDENT"
+	    "$FINDENT" -v
+	    echo "wfindent: indented files: 0"
+	    exit $?
+	 fi
+	 case "$1" in
+	    "-h"|"-H") "$FINDENT" "$1"
+	               exit $?
+		       ;;
+	 esac
+	 if [ "$1" != "-q" ] ; then
+	    fparms="$fparms $1" 
+	 else
+	    echo "wfindent: ignored flag -q"
+	    echo "          use $FINDENT -q < filename"
+	 fi
+	 shift
+	 ;;
    esac
 done
 tmp=`mktemp`
diff --git a/findent/scripts/wfindent.tmpl b/findent/scripts/wfindent.tmpl
--- a/findent/scripts/wfindent.tmpl
+++ b/findent/scripts/wfindent.tmpl
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Id: wfindent.tmpl 129 2016-08-11 13:47:39Z willem_vermin $
+# $Id: wfindent.tmpl 145 2016-11-13 16:16:33Z willem_vermin $
 # vim: filetype=sh
 #
 # in-place indenting of fortran sources using findent
@@ -12,7 +12,16 @@
 # otherwize an error message is printed.
 #
 
+# the location of findent, replace with correct location:
 FINDENT=findent-location
+if ! "$FINDENT" -v >/dev/null 2>&1 ; then
+   FINDENT="findent"   # try if findent is in PATH
+   if ! "$FINDENT" -v >/dev/null 2>&1 ; then
+      echo "$0: findent not found, exiting"
+      exit 1
+   fi
+fi
+echo "$0 using: "`"$FINDENT" -v`
 parms=$( getopt -o a:b:c:C:d:e:E:f:F:hHi:I:j:k:l:L:m:o:qr:R:s:t:vw:x: -- "$@" )
 if [ $? -ne 0 ] ; then
    exit 1
