willem

diff --git a/findent/src/test/tester b/findent/src/test/tester
--- a/findent/src/test/tester
+++ b/findent/src/test/tester
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/bin/sh
+echo "TESTING FINDENT ... "
+gfortran=gfortran
+$gfortran -v > /dev/null 2>&1  || { echo "Cannot compile: gfortran not installed" ; gfortran=: ; }
 rc=0
 exe=${1:-../findent}
 $exe -v
@@ -14,7 +17,7 @@ for i in *.f ; do
 	 ;;
    esac
 
-   gfortran -fcoarray=single -cpp $format $i >/dev/null 2>&1
+   $gfortran -fcoarray=single -cpp $format $i >/dev/null 2>&1
    if [ $? -ne 0 ] ; then
       echo -n " original program does not compile "
       rc=1
@@ -54,10 +57,11 @@ for i in *.f ; do
 	 format="-ffixed-form -ffixed-line-length-none -fd-lines-as-comments"
 	 ;;
    esac
-   gfortran -fcoarray=single -cpp $format $i.try.f >/dev/null 2>&1
+   $gfortran -fcoarray=single -cpp $format $i.try.f >/dev/null 2>&1
    if [ $? -ne 0 ] ; then
       echo "        converted program does not compile "
       rc=1
    fi
 done
+echo "END TESTING FINDENT rc=$rc"
 exit $rc
